[WeatherSite] Fix error for Pages/Index.cshtml.cs
- error CS0305: Using the generic type 'IEnumerable<T>' requires 1 type arguments
- error CS4001: Cannot await 'method group'